image: docker.io/jangorecki/r-pkg
services:
- postgres

variables:
  POSTGRES_PASSWORD: postgres

pages:
  script:
    # non-R dependencies
    - apt-get update -qq
    - apt-get -qq install -y libpq-dev
    # install deps
    - Rscript -e 'install.packages(c("R6","data.table"), repos=c("https://cran.rstudio.com","https://Rdatatable.github.io/data.table"))'
    # install suggests including cascades
    - Rscript -e 'install.packages(c("Rserve","RSclient","big.data.table","microbenchmarkCore","logR"), repos=c("http://rforge.net", paste0("https://", c("cran.rstudio.com","jangorecki.github.io/big.data.table","olafmersmann.github.io/drat","jangorecki.github.io/logR"))))'
    # build pkg
    - R CMD build .
    # run check
    - R CMD check $(ls -1t *.tar.gz | head -n 1) --no-manual --as-cran
    # produce artifacts
    - Rscript -e 'drat::insertArtifacts(repodir="public", repo.url="https://jangorecki.gitlab.io/data.cube", repo.cran=TRUE)'
  artifacts:
    paths:
      - public
