image: jangorecki/r-base-dev
before_script:
  - Rscript -e 'install.packages(c("R6","data.table","knitr"), repos="https://cran.rstudio.com")'
test:
  script:
    - R CMD build . --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-manual --as-cran
